spring:
  application:
    name: Springdoc
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.openapi.springdoc.model.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  packages-to-scan:
    - com.openapi.springdoc.controller

